apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  - name: postgres
    image: postgres
    environments:
      POSTGRES_PASSWORD: password
