apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config
data:
  config: |
    address-pools:
    - name: configmap-example
      protocol: layer2
      addresses:
      - 192.168.4.240-192.168.4.250
